mlnx-ofa_kernel-4.6-OFED.4.6.1.0.1.1.ga2cfe08.src.rpm from http://www.mellanox.com/downloads/ofed/MLNX_OFED-4.6-1.0.1.1/MLNX_OFED_SRC-4.6-1.0.1.1.tgz

diff --git a/ofed_scripts/configure b/ofed_scripts/configure
--- a/ofed_scripts/configure
+++ b/ofed_scripts/configure
@@ -178,6 +178,12 @@ Usage:  `basename $0` [options]
 
     --block-request-module     Prevent drivers from using request_module function [no]
 
+    --with-bf-device-emulation    make CONFIG_BF_DEVICE_EMULATION=y [no]
+    --without-bf-device-emulation    [yes]
+
+    --with-bf-power-failure-event make CONFIG_BF_POWER_FAILURE_EVENT=y [no]
+    --without-bf-power-failure-event [yes]
+
     --help - print out options
 
 
@@ -269,8 +275,11 @@ CONFIG_INFINIBAND_ADDR_TRANS_CONFIGFS=''
 CONFIG_INFINIBAND_USER_MEM=${CONFIG_INFINIBAND_USER_MEM:-''}
 
 CONFIG_MLX4_CORE=${CONFIG_MLX4_CORE:-''}
+CONFIG_MLX4_CORE_GEN2=${CONFIG_MLX4_CORE_GEN2:-'y'}
 CONFIG_MLXFW=${CONFIG_MLXFW:-''}
 CONFIG_MLX5_ACCEL=${CONFIG_MLX5_ACCEL:-''}
+CONFIG_MLX5_EN_ARFS=${CONFIG_MLX5_EN_ARFS:-''}
+CONFIG_MLX5_EN_RXNFC=${CONFIG_MLX5_EN_RXNFC:-''}
 CONFIG_MLX5_EN_TLS=${CONFIG_MLX5_EN_TLS:-''}
 CONFIG_MLX5_EN_IPSEC=${CONFIG_MLX5_EN_IPSEC:-''}
 CONFIG_MLX5_FPGA=${CONFIG_MLX5_FPGA:-''}
@@ -281,7 +290,6 @@ CONFIG_MLX5_CORE_EN_DCB=${CONFIG_MLX5_CORE_EN_DCB:-''}
 CONFIG_MLX5_MPFS=${CONFIG_MLX5_MPFS:-''}
 CONFIG_MLX5_ESWITCH=${CONFIG_MLX5_ESWITCH:-''}
 CONFIG_MLX5_CORE_IPOIB=${CONFIG_MLX5_CORE_IPOIB:-''}
-CONFIG_MLX5_INNER_RSS=${CONFIG_MLX5_INNER_RSS:-''}
 CONFIG_MLX5_EN_SPECIAL_SQ=${CONFIG_MLX5_EN_SPECIAL_SQ:-''}
 CONFIG_MLX4_EN=${CONFIG_MLX4_EN:-''}
 CONFIG_MLX4_INFINIBAND=${CONFIG_MLX4_INFINIBAND:-''}
@@ -331,6 +339,9 @@ CONFIG_INFINIBAND_WQE_FORMAT=${CONFIG_INFINIBAND_WQE_FORMAT:-''}
 CONFIG_INFINIBAND_PA_MR=${CONFIG_INFINIBAND_PA_MR:-''}
 
 CONFIG_MLNX_BLOCK_REQUEST_MODULE=${CONFIG_MLNX_BLOCK_REQUEST_MODULE:-''}
+
+CONFIG_BF_DEVICE_EMULATION=${CONFIG_BF_DEVICE_EMULATION:-''}
+CONFIG_BF_POWER_FAILURE_EVENT=${CONFIG_BF_POWER_FAILURE_EVENT:-''}
 
 main()
 {
@@ -642,10 +653,11 @@ main()
                             CONFIG_MLX5_CORE="m"
                             CONFIG_MLX5_CORE_EN="y"
                             CONFIG_MLX5_CORE_EN_DCB="y"
+                            CONFIG_MLX5_EN_ARFS="y"
+                            CONFIG_MLX5_EN_RXNFC="y"
                             CONFIG_MLX5_MPFS="y"
                             CONFIG_MLX5_ESWITCH="y"
                             CONFIG_MLX5_CORE_IPOIB="y"
-                            CONFIG_MLX5_INNER_RSS="y"
                             CONFIG_MLX5_EN_SPECIAL_SQ="y"
                             CONFIG_MLX5_INFINIBAND="m"
                             CONFIG_BACKPORT_LRO="m"
@@ -656,10 +668,11 @@ main()
                             CONFIG_MLX5_CORE="m"
                             CONFIG_MLX5_CORE_EN=
                             CONFIG_MLX5_CORE_EN_DCB=
+                            CONFIG_MLX5_EN_ARFS=
+                            CONFIG_MLX5_EN_RXNFC=
                             CONFIG_MLX5_MPFS=
                             CONFIG_MLX5_ESWITCH=
                             CONFIG_MLX5_CORE_IPOIB=
-                            CONFIG_MLX5_INNER_RSS=
                             CONFIG_MLX5_INFINIBAND=
                             CONFIG_BACKPORT_LRO="m"
                             CONFIG_MLX5_DEBUG="y"
@@ -669,10 +682,11 @@ main()
                             CONFIG_MLX5_CORE="m"
                             CONFIG_MLX5_CORE_EN=
                             CONFIG_MLX5_CORE_EN_DCB=
+                            CONFIG_MLX5_EN_ARFS=
+                            CONFIG_MLX5_EN_RXNFC=
                             CONFIG_MLX5_MPFS=
                             CONFIG_MLX5_ESWITCH=
                             CONFIG_MLX5_CORE_IPOIB=
-                            CONFIG_MLX5_INNER_RSS=
                             CONFIG_MLX5_INFINIBAND="m"
                             CONFIG_BACKPORT_LRO="m"
                             CONFIG_MLX5_DEBUG="y"
@@ -682,11 +696,12 @@ main()
                             CONFIG_MLX5_CORE="m"
                             CONFIG_MLX5_CORE_EN="y"
                             CONFIG_MLX5_CORE_EN_DCB="y"
+                            CONFIG_MLX5_EN_ARFS="y"
+                            CONFIG_MLX5_EN_RXNFC="y"
                             CONFIG_MLX5_MPFS="y"
                             CONFIG_MLX5_ESWITCH="y"
                             CONFIG_MLX5_CORE_IPOIB=
                             CONFIG_MLX5_EN_SPECIAL_SQ="y"
-                            CONFIG_MLX5_INNER_RSS="y"
                             CONFIG_MLX5_INFINIBAND=
                             CONFIG_BACKPORT_LRO="m"
                             CONFIG_MLX5_DEBUG="y"
@@ -696,10 +711,11 @@ main()
                             CONFIG_MLX5_CORE="m"
                             CONFIG_MLX5_CORE_EN="y"
                             CONFIG_MLX5_CORE_EN_DCB="y"
+                            CONFIG_MLX5_EN_ARFS="y"
+                            CONFIG_MLX5_EN_RXNFC="y"
                             CONFIG_MLX5_MPFS="y"
                             CONFIG_MLX5_ESWITCH="y"
                             CONFIG_MLX5_CORE_IPOIB=
-                            CONFIG_MLX5_INNER_RSS="y"
                             CONFIG_MLX5_INFINIBAND="m"
                             CONFIG_BACKPORT_LRO="m"
                             CONFIG_MLX5_DEBUG="y"
@@ -709,10 +725,11 @@ main()
                             CONFIG_MLX5_CORE="m"
                             CONFIG_MLX5_CORE_EN=
                             CONFIG_MLX5_CORE_EN_DCB=
+                            CONFIG_MLX5_EN_ARFS=
+                            CONFIG_MLX5_EN_RXNFC=
                             CONFIG_MLX5_MPFS=
                             CONFIG_MLX5_ESWITCH=
                             CONFIG_MLX5_CORE_IPOIB="y"
-                            CONFIG_MLX5_INNER_RSS=
                             CONFIG_MLX5_INFINIBAND="m"
                             CONFIG_BACKPORT_LRO="m"
                             CONFIG_MLX5_DEBUG="y"
@@ -728,20 +745,22 @@ main()
                             CONFIG_MLX5_CORE="m"
                             CONFIG_MLX5_CORE_EN="y"
                             CONFIG_MLX5_CORE_EN_DCB="y"
+                            CONFIG_MLX5_EN_ARFS="y"
+                            CONFIG_MLX5_EN_RXNFC="y"
                             CONFIG_MLX5_MPFS="y"
                             CONFIG_MLX5_ESWITCH="y"
                             CONFIG_MLX5_CORE_IPOIB="y"
-                            CONFIG_MLX5_INNER_RSS="y"
                             CONFIG_MLX5_EN_SPECIAL_SQ="y"
                         ;;
                         --without-mlx5_core-mod)
                             CONFIG_MLX5_CORE=
                             CONFIG_MLX5_CORE_EN=
                             CONFIG_MLX5_CORE_EN_DCB=
+                            CONFIG_MLX5_EN_ARFS=
+                            CONFIG_MLX5_EN_RXNFC=
                             CONFIG_MLX5_MPFS=
                             CONFIG_MLX5_ESWITCH=
                             CONFIG_MLX5_CORE_IPOIB=
-                            CONFIG_MLX5_INNER_RSS=
                             CONFIG_MLX5_EN_SPECIAL_SQ=
                         ;;
                         --without-mlx4-mod)
@@ -753,10 +772,11 @@ main()
                             CONFIG_MLX5_CORE=
                             CONFIG_MLX5_CORE_EN=
                             CONFIG_MLX5_CORE_EN_DCB=
+                            CONFIG_MLX5_EN_ARFS=
+                            CONFIG_MLX5_EN_RXNFC=
                             CONFIG_MLX5_MPFS=
                             CONFIG_MLX5_ESWITCH=
                             CONFIG_MLX5_CORE_IPOIB=
-                            CONFIG_MLX5_INNER_RSS=
                             CONFIG_MLX5_EN_SPECIAL_SQ=
                             CONFIG_MLX5_INFINIBAND=
                             CONFIG_MLX5_DEBUG=
@@ -788,20 +808,22 @@ main()
                             CONFIG_MLX5_CORE="m"
                             CONFIG_MLX5_CORE_EN="y"
                             CONFIG_MLX5_CORE_EN_DCB="y"
+                            CONFIG_MLX5_EN_ARFS="y"
+                            CONFIG_MLX5_EN_RXNFC="y"
                             CONFIG_MLX5_MPFS="y"
                             CONFIG_MLX5_ESWITCH="y"
                             CONFIG_MLX5_CORE_IPOIB="y"
-                            CONFIG_MLX5_INNER_RSS="y"
                             CONFIG_MLX5_INFINIBAND="m"
                         ;;
                         --without-mlx5_inf-mod)
                             CONFIG_MLX5_INFINIBAND=
                             CONFIG_MLX5_CORE_EN=
                             CONFIG_MLX5_CORE_EN_DCB=
+                            CONFIG_MLX5_EN_ARFS=
+                            CONFIG_MLX5_EN_RXNFC=
                             CONFIG_MLX5_MPFS=
                             CONFIG_MLX5_ESWITCH=
                             CONFIG_MLX5_CORE_IPOIB=
-                            CONFIG_MLX5_INNER_RSS=
                         ;;
                         --with-mlx4_fc-mod)
                             CONFIG_MLX4_CORE="m"
@@ -947,6 +969,18 @@ main()
                         ;;
                         --block-request-module)
                         CONFIG_MLNX_BLOCK_REQUEST_MODULE="y"
+                        ;;
+                        --with-bf-device-emulation)
+                        CONFIG_BF_DEVICE_EMULATION="y"
+                        ;;
+                        --without-bf-device-emulation)
+                        CONFIG_BF_DEVICE_EMULATION=
+                        ;;
+                        --with-bf-power-failure-event)
+                        CONFIG_BF_POWER_FAILURE_EVENT="y"
+                        ;;
+                        --without-bf-power-failure-event)
+                        CONFIG_BF_POWER_FAILURE_EVENT=
                         ;;
 
                         -h | --help)
@@ -1192,6 +1226,14 @@ if [ "X${CONFIG_MLX5_EN_IPSEC}" == "Xy" ]; then
     fi
 fi
 
+check_autofconf CONFIG_RFS_ACCEL
+if [ "X${CONFIG_MLX5_EN_ARFS=}" == "Xy" ]; then
+    if ! [ "X${CONFIG_RFS_ACCEL=}" == "X1" ]; then
+        echo "Warning: CONFIG_RFS_ACCEL is not enabled in the kernel, cannot enable CONFIG_MLX5_EN_ARFS."
+        CONFIG_MLX5_EN_ARFS=
+    fi
+fi
+
 check_autofconf CONFIG_TLS_DEVICE
 if [ "X${CONFIG_MLX5_EN_TLS=}" == "Xy" ]; then
     if ! [ "X${CONFIG_TLS_DEVICE=}" == "X1" ]; then
@@ -1295,9 +1337,12 @@ CONFIG_INFINIBAND_ADDR_TRANS_CONFIGFS=${CONFIG_INFINIBAND_ADDR_TRANS_CONFIGFS}
 CONFIG_INFINIBAND_USER_MEM=${CONFIG_INFINIBAND_USER_MEM}
 
 CONFIG_MLX4_CORE=${CONFIG_MLX4_CORE}
+CONFIG_MLX4_CORE_GEN2=${CONFIG_MLX4_CORE_GEN2}
 CONFIG_MLXFW=${CONFIG_MLXFW}
 CONFIG_MLX5_ACCEL=${CONFIG_MLX5_ACCEL}
 CONFIG_MLX5_EN_TLS=${CONFIG_MLX5_EN_TLS}
+CONFIG_MLX5_EN_ARFS=${CONFIG_MLX5_EN_ARFS}
+CONFIG_MLX5_EN_RXNFC=${CONFIG_MLX5_EN_RXNFC}
 CONFIG_MLX5_EN_IPSEC=${CONFIG_MLX5_EN_IPSEC}
 CONFIG_MLX5_FPGA=${CONFIG_MLX5_FPGA}
 CONFIG_MLX5_FPGA_TOOLS=${CONFIG_MLX5_FPGA_TOOLS}
@@ -1307,7 +1352,6 @@ CONFIG_MLX5_CORE_EN_DCB=${CONFIG_MLX5_CORE_EN_DCB}
 CONFIG_MLX5_MPFS=${CONFIG_MLX5_MPFS}
 CONFIG_MLX5_ESWITCH=${CONFIG_MLX5_ESWITCH}
 CONFIG_MLX5_CORE_IPOIB=${CONFIG_MLX5_CORE_IPOIB}
-CONFIG_MLX5_INNER_RSS=${CONFIG_MLX5_INNER_RSS}
 CONFIG_MLX5_EN_SPECIAL_SQ=${CONFIG_MLX5_EN_SPECIAL_SQ}
 CONFIG_MLX4_EN=${CONFIG_MLX4_EN}
 CONFIG_MLX4_EN_DCB=${CONFIG_MLX4_EN_DCB}
@@ -1363,6 +1407,9 @@ CONFIG_INFINIBAND_PA_MR=${CONFIG_INFINIBAND_PA_MR}
 
 CONFIG_MLNX_BLOCK_REQUEST_MODULE=${CONFIG_MLNX_BLOCK_REQUEST_MODULE}
 
+CONFIG_BF_DEVICE_EMULATION=${CONFIG_BF_DEVICE_EMULATION}
+
+CONFIG_BF_POWER_FAILURE_EVENT=${CONFIG_BF_POWER_FAILURE_EVENT}
 EOFCONFIG
         echo "Created ${CONFIG}:"
         cat ${CWD}/${CONFIG}
@@ -1458,6 +1505,11 @@ if [ "X${CONFIG_MLX4_CORE}" == "Xm" ]; then
 else
         DEFINE_MLX4_CORE="#undef CONFIG_MLX4_CORE"
 fi
+if [ "${CONFIG_MLX4_CORE_GEN2}" == "y" ]; then
+        DEFINE_MLX4_CORE_GEN2="#undef CONFIG_MLX4_CORE_GEN2\n#define CONFIG_MLX4_CORE_GEN2 1"
+else
+        DEFINE_MLX4_CORE_GEN2="#undef CONFIG_MLX4_CORE_GEN2"
+fi
 if [ "X${CONFIG_MLXFW}" == "Xm" ]; then
         DEFINE_MLXFW="#undef CONFIG_MLXFW\n#define CONFIG_MLXFW 1"
 else
@@ -1467,6 +1519,16 @@ if [ "X${CONFIG_MLX5_ACCEL}" == "Xy" ]; then
         DEFINE_MLX5_ACCEL="#undef CONFIG_MLX5_ACCEL\n#define CONFIG_MLX5_ACCEL 1"
 else
         DEFINE_MLX5_ACCEL="#undef CONFIG_MLX5_ACCEL"
+fi
+if [ "X${CONFIG_MLX5_EN_ARFS}" == "Xy" ]; then
+        DEFINE_MLX5_EN_ARFS="#undef CONFIG_MLX5_EN_ARFS\n#define CONFIG_MLX5_EN_ARFS 1"
+else
+        DEFINE_MLX5_EN_ARFS="#undef CONFIG_MLX5_EN_ARFS"
+fi
+if [ "X${CONFIG_MLX5_EN_RXNFC}" == "Xy" ]; then
+        DEFINE_MLX5_EN_RXNFC="#undef CONFIG_MLX5_EN_RXNFC\n#define CONFIG_MLX5_EN_RXNFC 1"
+else
+        DEFINE_MLX5_EN_RXNFC="#undef CONFIG_MLX5_EN_RXNFC"
 fi
 if [ "X${CONFIG_MLX5_EN_TLS}" == "Xy" ]; then
         DEFINE_MLX5_EN_TLS="#undef CONFIG_MLX5_EN_TLS\n#define CONFIG_MLX5_EN_TLS 1"
@@ -1517,11 +1579,6 @@ if [ "X${CONFIG_MLX5_CORE_IPOIB}" == "Xy" ]; then
         DEFINE_MLX5_CORE_IPOIB="#undef CONFIG_MLX5_CORE_IPOIB\n#define CONFIG_MLX5_CORE_IPOIB 1"
 else
         DEFINE_MLX5_CORE_IPOIB="#undef CONFIG_MLX5_CORE_IPOIB"
-fi
-if [ "X${CONFIG_MLX5_INNER_RSS}" == "Xy" ]; then
-        DEFINE_MLX5_INNER_RSS="#undef CONFIG_MLX5_INNER_RSS\n#define CONFIG_MLX5_INNER_RSS 1"
-else
-        DEFINE_MLX5_INNER_RSS="#undef CONFIG_MLX5_INNER_RSS"
 fi
 if [ "X${CONFIG_MLX5_EN_SPECIAL_SQ}" == "Xy" ]; then
         DEFINE_MLX5_EN_SPECIAL_SQ="#undef CONFIG_MLX5_EN_SPECIAL_SQ\n#define CONFIG_MLX5_EN_SPECIAL_SQ 1"
@@ -1770,6 +1827,16 @@ else
         DEFINE_CONFIG_MLNX_BLOCK_REQUEST_MODULE="#undef CONFIG_MLNX_BLOCK_REQUEST_MODULE"
 fi
 
+if [ "X${CONFIG_BF_DEVICE_EMULATION}" == "Xy" ]; then
+        DEFINE_CONFIG_BF_DEVICE_EMULATION="#undef CONFIG_BF_DEVICE_EMULATION\n#define CONFIG_BF_DEVICE_EMULATION 1"
+else
+        DEFINE_CONFIG_BF_DEVICE_EMULATION="#undef CONFIG_BF_DEVICE_EMULATION"
+fi
+if [ "X${CONFIG_BF_POWER_FAILURE_EVENT}" == "Xy" ]; then
+        DEFINE_CONFIG_BF_POWER_FAILURE_EVENT="#undef CONFIG_BF_POWER_FAILURE_EVENT\n#define CONFIG_BF_POWER_FAILURE_EVENT 1"
+else
+        DEFINE_CONFIG_BF_POWER_FAILURE_EVENT="#undef CONFIG_BF_POWER_FAILURE_EVENT"
+fi
 
 cat > ${AUTOCONF_H} << EOFAUTOCONF
 #ifndef __OFED_BUILD__
@@ -1806,8 +1873,11 @@ $(echo -e "${DEFINE_SCSI_ISCSI_ATTRS}" | grep -v undef)
 $(echo -e "${DEFINE_ISCSI_TCP}" | grep -v undef)
 $(echo -e "${DEFINE_E_IPOIB}" | grep -v undef)
 $(echo -e "${DEFINE_MLX4_CORE}" | grep -v undef)
+$(echo -e "${DEFINE_MLX4_CORE_GEN2}" | grep -v undef)
 $(echo -e "${DEFINE_MLXFW}" | grep -v undef)
 $(echo -e "${DEFINE_MLX5_ACCEL}" | grep -v undef)
+$(echo -e "${DEFINE_MLX5_EN_ARFS}" | grep -v undef)
+$(echo -e "${DEFINE_MLX5_EN_RXNFC}" | grep -v undef)
 $(echo -e "${DEFINE_MLX5_EN_TLS}" | grep -v undef)
 $(echo -e "${DEFINE_MLX5_EN_IPSEC}" | grep -v undef)
 $(echo -e "${DEFINE_MLX5_FPGA}" | grep -v undef)
@@ -1818,7 +1888,6 @@ $(echo -e "${DEFINE_MLX5_CORE_EN_DCB}" | grep -v undef)
 $(echo -e "${DEFINE_MLX5_MPFS}" | grep -v undef)
 $(echo -e "${DEFINE_MLX5_ESWITCH}" | grep -v undef)
 $(echo -e "${DEFINE_MLX5_CORE_IPOIB}" | grep -v undef)
-$(echo -e "${DEFINE_MLX5_INNER_RSS}" | grep -v undef)
 $(echo -e "${DEFINE_MLX5_EN_SPECIAL_SQ}" | grep -v undef)
 $(echo -e "${DEFINE_MLX4_EN}" | grep -v undef)
 $(echo -e "${DEFINE_MLX4_IB_DEBUG_FS}" | grep -v undef)
@@ -1853,6 +1922,8 @@ $(echo -e "${DEFINE_INFINIBAND_ON_DEMAND_PAGING}" | grep -v undef)
 $(echo -e "${DEFINE_INFINIBAND_ON_WQE_FORMAT}" | grep -v undef)
 $(echo -e "${DEFINE_INFINIBAND_PA_MR}" | grep -v undef)
 $(echo -e "${DEFINE_CONFIG_MLNX_BLOCK_REQUEST_MODULE}" | grep -v undef)
+$(echo -e "${DEFINE_CONFIG_BF_DEVICE_EMULATION}" | grep -v undef)
+$(echo -e "${DEFINE_CONFIG_BF_POWER_FAILURE_EVENT}" | grep -v undef)
 
 #else
 #undef CONFIG_COMPAT_VERSION
@@ -1877,9 +1948,12 @@ $(echo -e "${DEFINE_CONFIG_MLNX_BLOCK_REQUEST_MODULE}" | grep -v undef)
 #undef CONFIG_INFINIBAND_USER_MEM
 
 #undef CONFIG_MLX4_CORE
+#undef CONFIG_MLX4_CORE_GEN2
 #undef CONFIG_MLXFW
 #undef CONFIG_MLX5_ACCEL
 #undef CONFIG_MLX5_EN_TLS
+#undef CONFIG_MLX5_EN_ARFS
+#undef CONFIG_MLX5_EN_RXNFC
 #undef CONFIG_MLX5_EN_IPSEC
 #undef CONFIG_MLX5_FPGA
 #undef CONFIG_MLX5_FPGA_TOOLS
@@ -1889,7 +1963,6 @@ $(echo -e "${DEFINE_CONFIG_MLNX_BLOCK_REQUEST_MODULE}" | grep -v undef)
 #undef CONFIG_MLX5_MPFS
 #undef CONFIG_MLX5_ESWITCH
 #undef CONFIG_MLX5_CORE_IPOIB
-#undef CONFIG_MLX5_INNER_RSS
 #undef CONFIG_MLX5_EN_SPECIAL_SQ
 #undef CONFIG_MLX4_DEBUG
 #undef CONFIG_MLX5_DEBUG
@@ -1939,6 +2012,9 @@ $(echo -e "${DEFINE_CONFIG_MLNX_BLOCK_REQUEST_MODULE}" | grep -v undef)
 #undef CONFIG_MLX4_IB_DEBUG_FS
 #undef CONFIG_E_IPOIB
 
+#undef CONFIG_BF_DEVICE_EMULATION
+#undef CONFIG_BF_POWER_FAILURE_EVENT
+
 $(echo -e "${DEFINE_INFINIBAND}")
 $(echo -e "${DEFINE_INFINIBAND_CORE_DUMMY}")
 $(echo -e "${DEFINE_INFINIBAND_IPOIB}")
@@ -1971,9 +2047,12 @@ $(echo -e "${DEFINE_SCSI_ISCSI_ATTRS}")
 $(echo -e "${DEFINE_ISCSI_TCP}")
 $(echo -e "${DEFINE_E_IPOIB}")
 $(echo -e "${DEFINE_MLX4_CORE}")
+$(echo -e "${DEFINE_MLX4_CORE_GEN2}")
 $(echo -e "${DEFINE_MLXFW}")
 $(echo -e "${DEFINE_MLX5_ACCEL}")
 $(echo -e "${DEFINE_MLX5_EN_TLS}")
+$(echo -e "${DEFINE_MLX5_EN_ARFS}")
+$(echo -e "${DEFINE_MLX5_EN_RXNFC}")
 $(echo -e "${DEFINE_MLX5_EN_IPSEC}")
 $(echo -e "${DEFINE_MLX5_FPGA}")
 $(echo -e "${DEFINE_MLX5_FPGA_TOOLS}")
@@ -1983,7 +2062,6 @@ $(echo -e "${DEFINE_MLX5_CORE_EN_DCB}")
 $(echo -e "${DEFINE_MLX5_MPFS}")
 $(echo -e "${DEFINE_MLX5_ESWITCH}")
 $(echo -e "${DEFINE_MLX5_CORE_IPOIB}")
-$(echo -e "${DEFINE_MLX5_INNER_RSS}")
 $(echo -e "${DEFINE_MLX5_EN_SPECIAL_SQ}")
 $(echo -e "${DEFINE_MLX4_EN}")
 $(echo -e "${DEFINE_MLX4_IB_DEBUG_FS}")
@@ -2024,6 +2102,8 @@ $(echo -e "${DEFINE_INFINIBAND_ON_DEMAND_PAGING}")
 $(echo -e "${DEFINE_INFINIBAND_ON_WQE_FORMAT}")
 $(echo -e "${DEFINE_INFINIBAND_PA_MR}")
 $(echo -e "${DEFINE_CONFIG_MLNX_BLOCK_REQUEST_MODULE}")
+$(echo -e "${DEFINE_CONFIG_BF_DEVICE_EMULATION}")
+$(echo -e "${DEFINE_CONFIG_BF_POWER_FAILURE_EVENT}")
 #endif
 
 EOFAUTOCONF
